### ISSUE TITLE
`edu-sync-cli fetch` failed with "Error: invalid type: map, expected a sequence at line 1 column 0"

### ISSUE THREAD

**Issue by definfo** [mkroening/edu-sync#22]
Running `edu-sync-cli fetch` on latest Git version raises following error:
```
➜ RUST_BACKTRACE=full ./target/debug/edu-sync-cli fetch
2025-04-20T06:33:38.022854Z ERROR edu_ws::ws: Could not deserialize response ok_err=invalid type: map, expected a sequence at line 1 column 0
2025-04-20T06:33:38.022921Z ERROR edu_ws::ws: Could not deserialize error err=errorcode: unknown variant `invalidparameter`, expected one of `accessexception`, `errorcoursecontextnotvalid`, `invalidtoken` at line 1 column 73
Error: invalid type: map, expected a sequence at line 1 column 0

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.95/src/backtrace.rs:27:14
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/core/src/result.rs:2009:27
   2: edu_sync_cli::fetch::Subcommand::run::{{closure}}
             at ./edu-sync-cli/src/fetch.rs:25:47
   3: edu_sync_cli::Subcommand::run::{{closure}}
             at ./edu-sync-cli/src/main.rs:35:57
   4: edu_sync_cli::main::{{closure}}
             at ./edu-sync-cli/src/main.rs:52:31
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/park.rs:284:63
   7: tokio::runtime::coop::with_budget
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/park.rs:284:31
  10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/context/blocking.rs:66:9
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  12: tokio::runtime::context::runtime::enter_runtime
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/context/runtime.rs:65:16
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  14: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/runtime.rs:370:45
  15: tokio::runtime::runtime::Runtime::block_on
             at /home/definfo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/runtime.rs:340:13
  16: edu_sync_cli::main
             at ./edu-sync-cli/src/main.rs:52:5
  17: core::ops::function::FnOnce::call_once
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  18: std::sys::backtrace::__rust_begin_short_backtrace
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:154:18
  19: std::rt::lang_start::{{closure}}
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/ops/function.rs:284:13
  21: std::panicking::try::do_call
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:557:40
  22: std::panicking::try
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:520:19
  23: std::panic::catch_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panic.rs:358:14
  24: std::rt::lang_start_internal::{{closure}}
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/rt.rs:174:48
  25: std::panicking::try::do_call
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:557:40
  26: std::panicking::try
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:520:19
  27: std::panic::catch_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panic.rs:358:14
  28: std::rt::lang_start_internal
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/rt.rs:174:20
  29: std::rt::lang_start
             at /nix/store/5fp2afgp2aafjpsfsxyxild2x95mdkpw-rust-default-1.84.0/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  30: main
  31: __libc_start_call_main
  32: __libc_start_main_alias_2
  33: _start
```

Sanitized configuration (content within `<>` are hidden):
```toml
# edusync.toml
parallel-downloads = 5

[accounts."<url>"]
user = "<user>"
site = "<description>"
site-url = "http://<url>/"
user-id = <id>
token = "<token>"
path = "<path>"

[accounts."<id>@<url>".courses]
```

**Comment by mkroening** [comment]
Thank you for your patience!

So what's happening here is that edu-sync gets an unexpected response from your Moodle Server. Could you try again with `RUST_LOG=debug`? That should print the response verbatim. Then we can figure out, what exactly is going wrong. You could either email me the full response or sanitize the response and post it here. :)

**Comment by definfo** [comment]
```
RUST_LOG=debug ./target/debug/edu-sync-cli fetch
2025-05-17T14:36:27.888145Z DEBUG reqwest::connect: starting new connection: http://<url>/    
2025-05-17T14:36:27.889299Z DEBUG hyper_util::client::legacy::connect::http: connecting to <ip>:80
2025-05-17T14:36:27.889476Z DEBUG hyper_util::client::legacy::connect::http: connected to <ip>:80
2025-05-17T14:36:28.050349Z DEBUG hyper_util::client::legacy::pool: pooling idle connection for ("http", <url>)
2025-05-17T14:36:28.050437Z DEBUG edu_ws::ws: response="{\"exception\":\"invalid_parameter_exception\",\"errorcode\":\"invalidparameter\",\"message\":\"Invalid parameter value detected\",\"debuginfo\":\"Unexpected keys (returnusercount) detected in parameter array.\"}"
2025-05-17T14:36:28.050501Z ERROR edu_ws::ws: Could not deserialize response ok_err=invalid type: map, expected a sequence at line 1 column 0
2025-05-17T14:36:28.050509Z ERROR edu_ws::ws: Could not deserialize error err=errorcode: unknown variant `invalidparameter`, expected one of `accessexception`, `errorcoursecontextnotvalid`, `invalidtoken` at line 1 column 73
Error: invalid type: map, expected a sequence at line 1 column 0
```

**Comment by mkroening** [comment]
Huh, apparently, your moodle instance is not happy about the `returnusercount` parameter to `core_enrol_get_users_courses`.

The documentation says
> returnusercount (Default to "1")
> 
> Include count of enrolled users for each course? This can add several seconds to the response time if a user is on several large courses, so set this to false if the value will not be used to improve performance.

So Edu Sync sets it to 0, to be faster.

Could you try the [returnusercount](https://github.com/mkroening/edu-sync/tree/returnusercount) branch? I pushed a test commit to check if it works for you without the parameter. If yes, we can solve this properly afterward.

**Comment by definfo** [comment]
> Huh, apparently, your moodle instance is not happy about the `returnusercount` parameter to `core_enrol_get_users_courses`.
> 
> The documentation says
> 
> > returnusercount (Default to "1")
> > Include count of enrolled users for each course? This can add several seconds to the response time if a user is on several large courses, so set this to false if the value will not be used to improve performance.
> 
> So Edu Sync sets it to 0, to be faster.
> 
> Could you try the [returnusercount](https://github.com/mkroening/edu-sync/tree/returnusercount?rgh-link-date=2025-05-17T15%3A38%3A06.000Z) branch? I pushed a test commit to check if it works for you without the parameter. If yes, we can solve this properly afterward.

This patch does resolve this param mismatch and `edu-sync-cli fetch` works correctly.
However, I was still facing another problem when I tried to sync courses (see log below):

```
2025-05-17T16:30:10.680025Z DEBUG edu_ws::ws: response="{\"exception\":\"moodle_exception\",\"errorcode\":\"errorinvalidparam\",\"message\":\"The param \\\"includestealthmodules\\\" is invalid.\"}"
2025-05-17T16:30:10.680111Z ERROR edu_ws::ws: Could not deserialize response ok_err=invalid type: map, expected a sequence at line 1 column 0
2025-05-17T16:30:10.680119Z ERROR edu_ws::ws: Could not deserialize error err=errorcode: unknown variant `errorinvalidparam`, expected one of `accessexception`, `errorcoursecontextnotvalid`, `invalidtoken` at line 1 column 63
Could not get contents for 1497 ICE4408P-Advanced Electronics from 1316@moodle.speit.sjtu.edu.cn (invalid type: map, expected a sequence at line 1 column 0). Giving up.
All resources are up to date.
```

Moodle's documentation indicates this API change: https://tracker.moodle.org/browse/MDL-63542
If I did not get it wrong, this Moodle instance is on a deprecated, unmaintained version (<3.5.3).
I have no idea if we should carry on backward compatibility on this version. 🤔

**Comment by mkroening** [comment]
Could you test https://github.com/mkroening/edu-sync/pull/24? :)

**Comment by definfo** [comment]
> Could you test [#24](https://github.com/mkroening/edu-sync/pull/24)? :)

It works perfectly. Thanks!
A minor suggestion is that you could mention the context (regarding Moodle API deprecation) for this error handling logic in code comments/docs or anywhere else :)

**Comment by mkroening** [comment]
Sure! Like this? :)

**Comment by definfo** [comment]
> Sure! Like this? :)

Great to see that!

**Comment by mkroening** [comment]
Published as [v0.3.2](https://github.com/mkroening/edu-sync/releases/tag/v0.3.2). :)
